sudo: required

services: docker

before_install:
  - docker login -u osaichan -p 67c45f0a-97b0-4106-b2fa-68fc0a2187e0
  - docker-compose up --build --d

script:
  - docker-compose exec --env "RAILS_ENV=test" web rails db:create
  - docker-compose exec --env "RAILS_ENV=test" web rails db:migrate
  - docker-compose exec --env "RAILS_ENV=test" web rails test